In [1]:
CORP = '035420'  # 네이버
YEARS = range(2020, 2026)
REPRT_CODES = {'11013': 'Q1', '11012': 'Q2누적', '11014': 'Q3누적', '11011': '연간(사업보고서)'}

records = []
for year in YEARS:
    for code, label in REPRT_CODES.items():
        try:
            fs = dart.finstate(CORP, year, reprt_code=code)
            if fs is not None and len(fs) > 0:
                fs = fs.copy()
                fs['bsns_year'] = year
                fs['reprt_code'] = code
                fs['reprt_label'] = label
                records.append(fs)
        except Exception as e:
            print(f"{year} {label} 수집 실패:", e)

raw = pd.concat(records, ignore_index=True)
raw.to_csv('../data/naver_financials_raw.csv', index=False, encoding='utf-8-sig')
print("원본 데이터 shape:", raw.shape)
raw[['bsns_year', 'reprt_label', 'account_nm', 'thstrm_amount']].head(15)

2020 Q1 수집 실패: name 'dart' is not defined
2020 Q2누적 수집 실패: name 'dart' is not defined
2020 Q3누적 수집 실패: name 'dart' is not defined
2020 연간(사업보고서) 수집 실패: name 'dart' is not defined
2021 Q1 수집 실패: name 'dart' is not defined
2021 Q2누적 수집 실패: name 'dart' is not defined
2021 Q3누적 수집 실패: name 'dart' is not defined
2021 연간(사업보고서) 수집 실패: name 'dart' is not defined
2022 Q1 수집 실패: name 'dart' is not defined
2022 Q2누적 수집 실패: name 'dart' is not defined
2022 Q3누적 수집 실패: name 'dart' is not defined
2022 연간(사업보고서) 수집 실패: name 'dart' is not defined
2023 Q1 수집 실패: name 'dart' is not defined
2023 Q2누적 수집 실패: name 'dart' is not defined
2023 Q3누적 수집 실패: name 'dart' is not defined
2023 연간(사업보고서) 수집 실패: name 'dart' is not defined
2024 Q1 수집 실패: name 'dart' is not defined
2024 Q2누적 수집 실패: name 'dart' is not defined
2024 Q3누적 수집 실패: name 'dart' is not defined
2024 연간(사업보고서) 수집 실패: name 'dart' is not defined
2025 Q1 수집 실패: name 'dart' is not defined
2025 Q2누적 수집 실패: name 'dart' is not defined
2025 Q3누적 수집 실패: name 'dart' is not defined
2025 연간(사업보고서) 수집 실패: name 'dart' is not defined

NameError: name 'pd' is not defined

In [2]:
import os
from dotenv import load_dotenv
import OpenDartReader
import pandas as pd

load_dotenv('../backend/.env')
DART_API_KEY = os.getenv('DART_API_KEY')

dart = OpenDartReader(DART_API_KEY)
print("연결 확인:", dart.company('035420')['corp_name'])

ModuleNotFoundError: No module named 'OpenDartReader'

In [3]:
import sys
print(sys.executable)

C:\Users\user\Desktop\M1-2\.venv\Scripts\python.exe

In [4]:
import sys
!{sys.executable} -m pip install opendartreader

Requirement already satisfied: opendartreader in C:\Users\user\Desktop\M1-2\.venv\Lib\site-packages (0.3.3)
Requirement already satisfied: beautifulsoup4>=4.14.3 in C:\Users\user\Desktop\M1-2\.venv\Lib\site-packages (from opendartreader) (4.15.0)
Requirement already satisfied: click>=8.3.3 in C:\Users\user\Desktop\M1-2\.venv\Lib\site-packages (from opendartreader) (8.5.0)
Requirement already satisfied: lxml>=6.1.0 in C:\Users\user\Desktop\M1-2\.venv\Lib\site-packages (from opendartreader) (6.1.3)
Requirement already satisfied: pandas>=2.2.0 in C:\Users\user\Desktop\M1-2\.venv\Lib\site-packages (from opendartreader) (3.0.5)
Requirement already satisfied: python-dotenv>=1.0.0 in C:\Users\user\Desktop\M1-2\.venv\Lib\site-packages (from opendartreader) (1.2.3)
Requirement already satisfied: requests>=2.31.0 in C:\Users\user\Desktop\M1-2\.venv\Lib\site-packages (from opendartreader) (2.34.2)
Requirement already satisfied: soupsieve>=1.6.1 in C:\Users\user\Desktop\M1-2\.venv\Lib\site-packages (from beautifulsoup4>=4.14.3->opendartreader) (2.9.2)
Requirement already satisfied: typing-extensions>=4.0.0 in C:\Users\user\Desktop\M1-2\.venv\Lib\site-packages (from beautifulsoup4>=4.14.3->opendartreader) (4.16.0)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\user\Desktop\M1-2\.venv\Lib\site-packages (from pandas>=2.2.0->opendartreader) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\user\Desktop\M1-2\.venv\Lib\site-packages (from pandas>=2.2.0->opendartreader) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\user\Desktop\M1-2\.venv\Lib\site-packages (from pandas>=2.2.0->opendartreader) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\user\Desktop\M1-2\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas>=2.2.0->opendartreader) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\user\Desktop\M1-2\.venv\Lib\site-packages (from requests>=2.31.0->opendartreader) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\user\Desktop\M1-2\.venv\Lib\site-packages (from requests>=2.31.0->opendartreader) (3.19)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\user\Desktop\M1-2\.venv\Lib\site-packages (from requests>=2.31.0->opendartreader) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\user\Desktop\M1-2\.venv\Lib\site-packages (from requests>=2.31.0->opendartreader) (2026.7.22)

Could not find platform independent libraries <prefix>

In [1]:
import os
from dotenv import load_dotenv
import OpenDartReader
import pandas as pd

load_dotenv('../backend/.env')
DART_API_KEY = os.getenv('DART_API_KEY')

dart = OpenDartReader(DART_API_KEY)
print("연결 확인:", dart.company('035420')['corp_name'])  # 네이버가 출력되면 성공

ModuleNotFoundError: No module named 'OpenDartReader'

In [1]:
import sys
print(sys.executable)

C:\Users\user\Desktop\M1-2\.venv\Scripts\python.exe

In [2]:
import sys, os
print("sys.executable:", sys.executable)
print("site-packages 경로 sys.path에 포함?:", [p for p in sys.path if 'site-packages' in p])
print("실제 폴더 존재?:", os.path.exists(r"C:\Users\user\Desktop\M1-2\.venv\Lib\site-packages\OpenDartReader"))

sys.executable: C:\Users\user\Desktop\M1-2\.venv\Scripts\python.exe
site-packages 경로 sys.path에 포함?: ['C:\\Users\\user\\Desktop\\M1-2\\.venv\\Lib\\site-packages']
실제 폴더 존재?: True

In [3]:
site_packages = r"C:\Users\user\Desktop\M1-2\.venv\Lib\site-packages"
import os
matches = [f for f in os.listdir(site_packages) if 'dart' in f.lower()]
print(matches)

['opendartreader', 'opendartreader-0.3.3.dist-info']

In [4]:
import opendartreader
print(dir(opendartreader))

['OpenDartReader', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', 'dart', 'dart_event', 'dart_finstate', 'dart_list', 'dart_regstate', 'dart_report', 'dart_share', 'dart_utils']

In [5]:
import opendartreader

dart = opendartreader.OpenDartReader(DART_API_KEY)
print("연결 확인:", dart.company('035420')['corp_name'])

NameError: name 'DART_API_KEY' is not defined

In [6]:
import os
from dotenv import load_dotenv
import opendartreader
import pandas as pd

load_dotenv('../backend/.env')
DART_API_KEY = os.getenv('DART_API_KEY')

dart = opendartreader.OpenDartReader(DART_API_KEY)
print("연결 확인:", dart.company('035420')['corp_name'])

연결 확인: 네이버(주)

In [7]:
CORP = '035420'  # 네이버
YEARS = range(2020, 2026)
REPRT_CODES = {'11013': 'Q1', '11012': 'Q2누적', '11014': 'Q3누적', '11011': '연간(사업보고서)'}

records = []
for year in YEARS:
    for code, label in REPRT_CODES.items():
        try:
            fs = dart.finstate(CORP, year, reprt_code=code)
            if fs is not None and len(fs) > 0:
                fs = fs.copy()
                fs['bsns_year'] = year
                fs['reprt_code'] = code
                fs['reprt_label'] = label
                records.append(fs)
        except Exception as e:
            print(f"{year} {label} 수집 실패:", e)

raw = pd.concat(records, ignore_index=True)
raw.to_csv('../data/naver_financials_raw.csv', index=False, encoding='utf-8-sig')
print("원본 데이터 shape:", raw.shape)
raw[['bsns_year', 'reprt_label', 'account_nm', 'thstrm_amount']].head(15)

원본 데이터 shape: (728, 24)

    bsns_year reprt_label  account_nm       thstrm_amount
0        2020          Q1        유동자산   6,533,603,337,706
1        2020          Q1       비유동자산   7,232,430,519,335
2        2020          Q1        자산총계  13,766,033,857,041
3        2020          Q1        유동부채   4,097,111,757,227
4        2020          Q1       비유동부채   2,213,685,558,800
5        2020          Q1        부채총계   6,310,797,316,027
6        2020          Q1         자본금      16,481,339,500
7        2020          Q1       이익잉여금   5,802,449,125,381
8        2020          Q1        자본총계   7,455,236,541,014
9        2020          Q1         매출액   1,732,064,462,097
10       2020          Q1        영업이익     221,495,078,328
11       2020          Q1  법인세차감전 순이익     253,869,866,940
12       2020          Q1   당기순이익(손실)     134,874,581,865
13       2020          Q1   당기순이익(손실)     134,874,581,865
14       2020          Q1        유동자산   1,044,023,184,863

In [8]:
target_items = ['매출액', '영업이익', '당기순이익(손실)', '자산총계', '부채총계', '자본총계', '영업활동으로인한현금흐름']

filtered = raw[raw['account_nm'].isin(target_items)][
    ['bsns_year', 'reprt_label', 'account_nm', 'thstrm_amount']
]
print(filtered['account_nm'].unique())
filtered.head(20)

<StringArray>
['자산총계', '부채총계', '자본총계', '매출액', '영업이익', '당기순이익(손실)']
Length: 6, dtype: str

    bsns_year reprt_label account_nm       thstrm_amount
2        2020          Q1       자산총계  13,766,033,857,041
5        2020          Q1       부채총계   6,310,797,316,027
8        2020          Q1       자본총계   7,455,236,541,014
9        2020          Q1        매출액   1,732,064,462,097
10       2020          Q1       영업이익     221,495,078,328
12       2020          Q1  당기순이익(손실)     134,874,581,865
13       2020          Q1  당기순이익(손실)     134,874,581,865
16       2020          Q1       자산총계   6,994,761,518,346
19       2020          Q1       부채총계   1,287,271,703,574
22       2020          Q1       자본총계   5,707,489,814,772
23       2020          Q1        매출액     917,960,548,836
24       2020          Q1       영업이익     325,456,163,738
26       2020          Q1  당기순이익(손실)     327,064,990,926
27       2020          Q1  당기순이익(손실)     327,064,990,926
30       2020        Q2누적       자산총계  14,675,445,319,033
33       2020        Q2누적       부채총계   6,717,594,049,563
36       2020        Q2누적       자본총계   7,957,851,269,470
37       2020        Q2누적        매출액   1,902,467,957,491
38       2020        Q2누적       영업이익     230,597,573,115
40       2020        Q2누적  당기순이익(손실)      90,682,203,810

In [9]:
print(raw['account_nm'].unique())

<StringArray>
[      '유동자산',      '비유동자산',       '자산총계',       '유동부채',      '비유동부채',
       '부채총계',        '자본금',      '이익잉여금',       '자본총계',        '매출액',
       '영업이익', '법인세차감전 순이익',  '당기순이익(손실)',      '총포괄손익',       '이자수익',
       '영업비용']
Length: 16, dtype: str

In [10]:
print("전체 계정명 목록:")
print(raw['account_nm'].unique())

print("\nfs_div(재무제표 구분) 값:")
print(raw['fs_div'].unique())  # 보통 CFS(연결), OFS(별도)

전체 계정명 목록:
<StringArray>
[      '유동자산',      '비유동자산',       '자산총계',       '유동부채',      '비유동부채',
       '부채총계',        '자본금',      '이익잉여금',       '자본총계',        '매출액',
       '영업이익', '법인세차감전 순이익',  '당기순이익(손실)',      '총포괄손익',       '이자수익',
       '영업비용']
Length: 16, dtype: str

fs_div(재무제표 구분) 값:
<StringArray>
['CFS', 'OFS']
Length: 2, dtype: str

In [11]:
# ① CFS(연결재무제표)만 필터링
cfs = raw[raw['fs_div'] == 'CFS'].copy()
print("CFS만 필터링:", cfs.shape)

# ② 현금흐름표는 별도 함수로 수집 (finstate_all 사용, 전체 재무제표 항목 포함)
cf_records = []
for year in YEARS:
    for code, label in REPRT_CODES.items():
        try:
            fs_all = dart.finstate_all(CORP, year, reprt_code=code, fs_div='CFS')
            if fs_all is not None and len(fs_all) > 0:
                fs_all = fs_all.copy()
                fs_all['bsns_year'] = year
                fs_all['reprt_code'] = code
                fs_all['reprt_label'] = label
                cf_records.append(fs_all)
        except Exception as e:
            print(f"{year} {label} 전체재무제표 수집 실패:", e)

full = pd.concat(cf_records, ignore_index=True)
print("전체 재무제표(finstate_all) shape:", full.shape)

# 현금흐름표 관련 계정명 찾기
cf_items = full[full['account_nm'].str.contains('현금흐름|영업활동', na=False)]
print(cf_items['account_nm'].unique())

CFS만 필터링: (364, 24)
reprt_code='11013', fs_div='CFS' (1분기보고서, 연결제무제표)'
reprt_code='11012', fs_div='CFS' (반기보고서, 연결제무제표)'
reprt_code='11014', fs_div='CFS' (3분기보고서, 연결제무제표)'
reprt_code='11011', fs_div='CFS' (사업보고서, 연결제무제표)'
reprt_code='11013', fs_div='CFS' (1분기보고서, 연결제무제표)'
reprt_code='11012', fs_div='CFS' (반기보고서, 연결제무제표)'
reprt_code='11014', fs_div='CFS' (3분기보고서, 연결제무제표)'
reprt_code='11011', fs_div='CFS' (사업보고서, 연결제무제표)'
reprt_code='11013', fs_div='CFS' (1분기보고서, 연결제무제표)'
reprt_code='11012', fs_div='CFS' (반기보고서, 연결제무제표)'
reprt_code='11014', fs_div='CFS' (3분기보고서, 연결제무제표)'
reprt_code='11011', fs_div='CFS' (사업보고서, 연결제무제표)'
reprt_code='11013', fs_div='CFS' (1분기보고서, 연결제무제표)'
reprt_code='11012', fs_div='CFS' (반기보고서, 연결제무제표)'
reprt_code='11014', fs_div='CFS' (3분기보고서, 연결제무제표)'
reprt_code='11011', fs_div='CFS' (사업보고서, 연결제무제표)'
reprt_code='11013', fs_div='CFS' (1분기보고서, 연결제무제표)'
reprt_code='11012', fs_div='CFS' (반기보고서, 연결제무제표)'
reprt_code='11014', fs_div='CFS' (3분기보고서, 연결제무제표)'
reprt_code='11011', fs_div='CFS' (사업보고서, 연결제무제표)'
reprt_code='11013', fs_div='CFS' (1분기보고서, 연결제무제표)'
reprt_code='11012', fs_div='CFS' (반기보고서, 연결제무제표)'
reprt_code='11014', fs_div='CFS' (3분기보고서, 연결제무제표)'
reprt_code='11011', fs_div='CFS' (사업보고서, 연결제무제표)'
전체 재무제표(finstate_all) shape: (4869, 22)
<StringArray>
[                  '영업활동현금흐름',            '영업으로부터 창출된 현금흐름',
                   '투자활동현금흐름',                   '재무활동현금흐름',
         '현금흐름위험회피 파생상품 평가손익',        '종속기업의 처분으로 인한 순현금흐름',
  '종속기업의 관계기업 전환 등으로 인한순현금흐름',   '종속기업의 관계기업 전환으로 인한 순현금흐름',
 '종속기업의 관계기업 전환 등으로 인한 순현금흐름',              '영업에서 창출된 현금흐름',
                  '재무활동 현금흐름',                  '투자활동 현금흐름',
                  '영업활동 현금흐름',          '현금흐름위험회피 파생상품평가손익']
Length: 14, dtype: str

In [12]:
# ① 현금흐름 항목만 추출 (CFS만)
cf = full[(full['fs_div']=='CFS') & (full['account_nm']=='영업활동으로부터 창출된 현금흐름')][
    ['bsns_year','reprt_label','thstrm_amount']
].copy()
cf['account_nm'] = '영업활동현금흐름'

# ② BS+IS(CFS) + 현금흐름 합치기
combined = pd.concat([
    cfs[['bsns_year','reprt_label','account_nm','thstrm_amount']],
    cf[['bsns_year','reprt_label','account_nm','thstrm_amount']]
], ignore_index=True)

# ③ 금액을 숫자로 변환 (콤마 제거)
combined['thstrm_amount'] = combined['thstrm_amount'].astype(str).str.replace(',', '', regex=False)
combined['thstrm_amount'] = pd.to_numeric(combined['thstrm_amount'], errors='coerce')

# ④ wide 형태로 피벗 (분기 하나당 한 줄, 계정과목이 컬럼으로)
pivot = combined.pivot_table(
    index=['bsns_year','reprt_label'],
    columns='account_nm',
    values='thstrm_amount',
    aggfunc='first'
).reset_index()

print(pivot.shape)
pivot

KeyError: 'fs_div'

In [13]:
print(full.columns.tolist())
full.head(3)

['rcept_no', 'reprt_code', 'bsns_year', 'corp_code', 'sj_div', 'sj_nm', 'account_id', 'account_nm', 'account_detail', 'thstrm_nm', 'thstrm_amount', 'frmtrm_nm', 'frmtrm_amount', 'ord', 'currency', 'thstrm_add_amount', 'frmtrm_q_nm', 'frmtrm_q_amount', 'frmtrm_add_amount', 'reprt_label', 'bfefrmtrm_nm', 'bfefrmtrm_amount']

,rcept_no,reprt_code,bsns_year,corp_code,sj_div,sj_nm,account_id,account_nm,account_detail,thstrm_nm,...,frmtrm_amount,ord,currency,thstrm_add_amount,frmtrm_q_nm,frmtrm_q_amount,frmtrm_add_amount,reprt_label,bfefrmtrm_nm,bfefrmtrm_amount
0,20200515002472,11013,2020,00266961,BS,재무상태표,ifrs-full_CurrentAssets,유동자산,-,제 22 기 1분기말,...,5643714459664,1,KRW,NaN,NaN,NaN,NaN,Q1,NaN,NaN
1,20200515002472,11013,2020,00266961,BS,재무상태표,ifrs-full_CashAndCashEquivalents,현금및현금성자산,-,제 22 기 1분기말,...,3740513761418,2,KRW,NaN,NaN,NaN,NaN,Q1,NaN,NaN
2,20200515002472,11013,2020,00266961,BS,재무상태표,dart_ShortTermDepositsNotClassifiedAsCashEquiv...,단기금융상품,-,제 22 기 1분기말,...,289910618872,3,KRW,NaN,NaN,NaN,NaN,Q1,NaN,NaN

In [14]:
# ① 현금흐름표(CF)에서 영업활동현금흐름만 추출 (fs_div 필터 불필요 - 이미 CFS로 수집됨)
cf = full[(full['sj_div']=='CF') & (full['account_nm']=='영업활동으로부터 창출된 현금흐름')][
    ['bsns_year','reprt_label','thstrm_amount']
].copy()
cf['account_nm'] = '영업활동현금흐름'

# ② BS+IS(cfs, 이전 셀에서 이미 CFS로 필터링됨) + 현금흐름 합치기
combined = pd.concat([
    cfs[['bsns_year','reprt_label','account_nm','thstrm_amount']],
    cf[['bsns_year','reprt_label','account_nm','thstrm_amount']]
], ignore_index=True)

# ③ 금액을 숫자로 변환 (콤마 제거)
combined['thstrm_amount'] = combined['thstrm_amount'].astype(str).str.replace(',', '', regex=False)
combined['thstrm_amount'] = pd.to_numeric(combined['thstrm_amount'], errors='coerce')

# ④ wide 형태로 피벗
pivot = combined.pivot_table(
    index=['bsns_year','reprt_label'],
    columns='account_nm',
    values='thstrm_amount',
    aggfunc='first'
).reset_index()

print(pivot.shape)
pivot

(24, 18)

account_nm,bsns_year,reprt_label,당기순이익(손실),매출액,법인세차감전 순이익,부채총계,비유동부채,비유동자산,영업비용,영업이익,유동부채,유동자산,이익잉여금,이자수익,자본금,자본총계,자산총계,총포괄손익
0,2020,Q1,1.348746e+11,1.732064e+12,2.538699e+11,6.310797e+12,2.213686e+12,7.232431e+12,NaN,2.214951e+11,4.097112e+12,6.533603e+12,5.802449e+12,NaN,1.648134e+10,7.455237e+12,1.376603e+13,NaN
1,2020,Q2누적,9.068220e+10,1.902468e+12,1.757673e+11,6.717594e+12,2.154746e+12,7.593540e+12,NaN,2.305976e+11,4.562848e+12,7.081905e+12,5.987388e+12,NaN,1.648134e+10,7.957851e+12,1.467545e+13,NaN
2,2020,Q3누적,2.353430e+11,1.360779e+12,3.615816e+11,8.040823e+12,7.685952e+11,5.245619e+12,NaN,2.917268e+11,7.272227e+12,1.020694e+13,6.233586e+12,NaN,1.648134e+10,7.411737e+12,1.545256e+13,NaN
3,2020,연간(사업보고서),8.449970e+11,5.304146e+12,1.633559e+12,8.759107e+12,8.473551e+11,6.469579e+12,NaN,1.215342e+12,7.911751e+12,1.054466e+13,6.654814e+12,NaN,1.648134e+10,8.255132e+12,1.701424e+13,NaN
4,2021,Q1,1.531452e+13,1.499070e+12,4.248960e+11,7.997815e+12,4.459144e+12,2.519402e+13,NaN,2.888331e+11,3.538672e+12,5.236989e+12,2.189957e+13,NaN,1.648134e+10,2.243319e+13,3.043101e+13,NaN
5,2021,Q2누적,5.405520e+11,1.663549e+12,6.471205e+11,8.431216e+12,4.795617e+12,2.674859e+13,NaN,3.356255e+11,3.635599e+12,4.946302e+12,2.245044e+13,NaN,1.648134e+10,2.326367e+13,3.169489e+13,NaN
6,2021,Q3누적,3.227262e+11,1.727255e+12,4.950257e+11,8.755051e+12,4.887117e+12,2.815552e+13,NaN,3.497720e+11,3.867933e+12,4.805362e+12,2.278017e+13,NaN,1.648134e+10,2.420583e+13,3.296088e+13,NaN
7,2021,연간(사업보고서),1.647763e+13,6.817600e+12,2.126400e+12,9.663630e+12,5.740311e+12,2.816313e+13,NaN,1.325478e+12,3.923319e+12,5.527878e+12,2.308041e+13,NaN,1.648134e+10,2.402738e+13,3.369101e+13,NaN
8,2022,Q1,1.513982e+11,1.845222e+12,2.566464e+11,1.002537e+13,5.634443e+12,2.769063e+13,NaN,3.017872e+11,4.390923e+12,6.001855e+12,2.317530e+13,NaN,1.648134e+10,2.366711e+13,3.369248e+13,NaN
9,2022,Q2누적,1.584744e+11,2.045781e+12,2.631774e+11,1.013183e+13,5.966891e+12,2.711281e+13,NaN,3.361511e+11,4.164943e+12,6.053242e+12,2.338603e+13,NaN,1.648134e+10,2.303422e+13,3.316605e+13,NaN
10,2022,Q3누적,2.315544e+11,2.057332e+12,3.747258e+11,1.008924e+13,5.283738e+12,2.846296e+13,NaN,3.302433e+11,4.805499e+12,5.970372e+12,2.359325e+13,NaN,1.648134e+10,2.434410e+13,3.443333e+13,NaN
11,2022,연간(사업보고서),6.731803e+11,8.220079e+12,1.083717e+12,1.044872e+13,4.968087e+12,2.745947e+13,NaN,1.304664e+12,5.480634e+12,6.439571e+12,2.364569e+13,NaN,1.648134e+10,2.345032e+13,3.389904e+13,NaN
12,2023,Q1,4.365522e+10,2.280443e+12,1.165854e+11,1.164942e+13,5.377375e+12,2.909808e+13,NaN,3.304921e+11,6.272046e+12,6.675250e+12,2.369751e+13,NaN,1.648134e+10,2.412391e+13,3.577333e+13,NaN
13,2023,Q2누적,2.867154e+11,2.407904e+12,4.211049e+11,1.123290e+13,5.430558e+12,2.826057e+13,NaN,3.726565e+11,5.802341e+12,6.494278e+12,2.396762e+13,NaN,1.648134e+10,2.352195e+13,3.475485e+13,NaN
14,2023,Q3누적,3.562068e+11,2.445292e+12,5.045386e+11,1.172866e+13,5.734796e+12,2.871228e+13,NaN,3.801807e+11,5.993860e+12,6.821496e+12,2.429025e+13,NaN,1.648134e+10,2.380512e+13,3.553377e+13,3.689266e+11
15,2023,연간(사업보고서),9.850178e+11,9.670644e+12,1.481396e+12,1.149983e+13,5.194260e+12,2.870975e+13,8.181823e+12,1.488820e+12,6.305569e+12,7.028076e+12,2.454436e+13,1.011111e+11,1.648134e+10,2.423800e+13,3.573783e+13,7.243692e+11
16,2024,Q1,5.558033e+11,2.526055e+12,6.601738e+11,1.125654e+13,5.478416e+12,2.820037e+13,2.086762e+12,4.392931e+11,5.778123e+12,7.598951e+12,2.493610e+13,3.203372e+10,1.648134e+10,2.454279e+13,3.579932e+13,3.586113e+11
17,2024,Q2누적,3.320565e+11,2.610486e+12,4.673515e+11,1.125754e+13,5.218733e+12,2.797329e+13,2.137801e+12,4.726851e+11,6.038809e+12,8.329008e+12,2.527330e+13,3.822086e+10,1.648134e+10,2.504475e+13,3.630229e+13,5.027290e+10
18,2024,Q3누적,5.300778e+11,2.715557e+12,6.532822e+11,1.114654e+13,5.243956e+12,2.788643e+13,2.190287e+12,5.252697e+11,5.902579e+12,9.415324e+12,2.567135e+13,4.806878e+10,1.648134e+10,2.615522e+13,3.730176e+13,1.002135e+12
19,2024,연간(사업보고서),1.931976e+12,1.073772e+13,2.322184e+12,1.116696e+13,5.074804e+12,2.879296e+13,8.758456e+12,1.979263e+12,6.092161e+12,9.374912e+12,2.596496e+13,1.735552e+11,1.648134e+10,2.700091e+13,3.816788e+13,2.630664e+12
20,2025,Q1,4.236613e+11,2.786783e+12,5.801085e+11,1.128440e+13,3.556047e+12,2.955714e+13,2.281482e+12,5.053013e+11,7.728357e+12,9.756883e+12,2.620723e+13,5.672220e+10,1.648134e+10,2.802962e+13,3.931402e+13,1.141128e+12
21,2025,Q2누적,4.973583e+11,2.915085e+12,6.836174e+11,1.141530e+13,3.771557e+12,2.941732e+13,2.393531e+12,5.215537e+11,7.643738e+12,9.933739e+12,2.663459e+13,5.599177e+10,1.648134e+10,2.793577e+13,3.935106e+13,-1.057787e+11
22,2025,Q3누적,7.347237e+11,3.138055e+12,8.568958e+11,1.197570e+13,3.900180e+12,2.991499e+13,2.567408e+12,5.706468e+11,8.075522e+12,1.085208e+13,2.721492e+13,5.321700e+10,1.648134e+10,2.879137e+13,4.076707e+13,7.926792e+11
23,2025,연간(사업보고서),1.818746e+12,1.203501e+13,2.420143e+12,1.213148e+13,4.112606e+12,3.015603e+13,9.826869e+12,2.208138e+12,8.018877e+12,1.092846e+13,2.762568e+13,2.225017e+11,1.648134e+10,2.895301e+13,4.108450e+13,1.937532e+12

In [15]:
df = pivot.copy()

# 컬럼명 영문으로 정리 (다루기 쉽게)
df = df.rename(columns={
    '매출액':'revenue', '영업이익':'operating_profit', '당기순이익(손실)':'net_income',
    '자산총계':'total_assets', '부채총계':'total_liabilities', '자본총계':'total_equity',
    '유동자산':'current_assets', '유동부채':'current_liabilities',
    '영업활동현금흐름':'operating_cf'
})

# 계산 지표 추가
df['operating_margin'] = df['operating_profit'] / df['revenue'] * 100        # 영업이익률(%)
df['net_margin'] = df['net_income'] / df['revenue'] * 100                    # 순이익률(%)
df['debt_ratio'] = df['total_liabilities'] / df['total_equity'] * 100        # 부채비율(%)
df['current_ratio'] = df['current_assets'] / df['current_liabilities'] * 100 # 유동비율(%)
df['equity_ratio'] = df['total_equity'] / df['total_assets'] * 100           # 자기자본비율(%)

# 분기말 날짜 만들기 (quarter → 날짜)
quarter_end = {'Q1':'-03-31', 'Q2누적':'-06-30', 'Q3누적':'-09-30', '연간(사업보고서)':'-12-31'}
df['date'] = df['bsns_year'].astype(str) + df['reprt_label'].map(quarter_end)

# 매출증가율(YoY)은 같은 분기 전년 대비이므로, 정렬 후 계산
df = df.sort_values(['reprt_label','bsns_year'])
df['revenue_yoy'] = df.groupby('reprt_label')['revenue'].pct_change() * 100
df = df.sort_values('date').reset_index(drop=True)

print(df[['date','revenue','operating_profit','net_income','debt_ratio','current_ratio','equity_ratio','operating_cf','revenue_yoy']])

KeyError: "['operating_cf'] not in index"

In [16]:
print(pivot.columns.tolist())

['bsns_year', 'reprt_label', '당기순이익(손실)', '매출액', '법인세차감전 순이익', '부채총계', '비유동부채', '비유동자산', '영업비용', '영업이익', '유동부채', '유동자산', '이익잉여금', '이자수익', '자본금', '자본총계', '자산총계', '총포괄손익']

In [17]:
print(full['sj_div'].unique())
cf_check = full[full['account_nm']=='영업활동으로부터 창출된 현금흐름']
print(cf_check.shape)
cf_check[['bsns_year','reprt_label','sj_div','account_nm','thstrm_amount']]

<StringArray>
['BS', 'CIS', 'CF', 'SCE']
Length: 4, dtype: str
(0, 22)

Empty DataFrame
Columns: [bsns_year, reprt_label, sj_div, account_nm, thstrm_amount]
Index: []

In [18]:
cf_all = full[full['sj_div']=='CF']
print(cf_all['account_nm'].unique())

<StringArray>
[              '영업활동현금흐름',        '영업으로부터 창출된 현금흐름',                   '이자수취',
                   '이자지급',              '배당금수취(영업)',              '법인세납부(환급)',
               '투자활동현금흐름',        '단기금융상품의 순감소(증가)',             '장기금융상품의 증가',
 '당기손익-공정가치금융자산의 순감소(증가)',
 ...
              '종속회사 유상증자',              '장기대여금의 감소',              '단기대여금의 감소',
              '장기대여금의 증가',              '단기대여금의 증가',      '기타투자활동으로 인한 현금유입액',
              '비유동차입금 상환',               '유동차입금 상환',              '단기대여금의 회수',
              '투자부동산의 취득']
Length: 128, dtype: str

In [19]:
cf = full[(full['sj_div']=='CF') & (full['account_nm']=='영업활동현금흐름')][
    ['bsns_year','reprt_label','thstrm_amount']
].copy()
cf['account_nm'] = '영업활동현금흐름'

combined = pd.concat([
    cfs[['bsns_year','reprt_label','account_nm','thstrm_amount']],
    cf[['bsns_year','reprt_label','account_nm','thstrm_amount']]
], ignore_index=True)

combined['thstrm_amount'] = combined['thstrm_amount'].astype(str).str.replace(',', '', regex=False)
combined['thstrm_amount'] = pd.to_numeric(combined['thstrm_amount'], errors='coerce')

pivot = combined.pivot_table(
    index=['bsns_year','reprt_label'],
    columns='account_nm',
    values='thstrm_amount',
    aggfunc='first'
).reset_index()

print(pivot.shape)
print(pivot.columns.tolist())

(24, 19)
['bsns_year', 'reprt_label', '당기순이익(손실)', '매출액', '법인세차감전 순이익', '부채총계', '비유동부채', '비유동자산', '영업비용', '영업이익', '영업활동현금흐름', '유동부채', '유동자산', '이익잉여금', '이자수익', '자본금', '자본총계', '자산총계', '총포괄손익']

In [20]:
df = pivot.copy()

df = df.rename(columns={
    '매출액':'revenue', '영업이익':'operating_profit', '당기순이익(손실)':'net_income',
    '자산총계':'total_assets', '부채총계':'total_liabilities', '자본총계':'total_equity',
    '유동자산':'current_assets', '유동부채':'current_liabilities',
    '영업활동현금흐름':'operating_cf'
})

df['operating_margin'] = df['operating_profit'] / df['revenue'] * 100
df['net_margin'] = df['net_income'] / df['revenue'] * 100
df['debt_ratio'] = df['total_liabilities'] / df['total_equity'] * 100
df['current_ratio'] = df['current_assets'] / df['current_liabilities'] * 100
df['equity_ratio'] = df['total_equity'] / df['total_assets'] * 100

quarter_end = {'Q1':'-03-31', 'Q2누적':'-06-30', 'Q3누적':'-09-30', '연간(사업보고서)':'-12-31'}
df['date'] = df['bsns_year'].astype(str) + df['reprt_label'].map(quarter_end)

df = df.sort_values(['reprt_label','bsns_year'])
df['revenue_yoy'] = df.groupby('reprt_label')['revenue'].pct_change() * 100
df = df.sort_values('date').reset_index(drop=True)

print(df[['date','revenue','operating_profit','net_income','debt_ratio','current_ratio','equity_ratio','operating_cf','revenue_yoy']])

account_nm        date       revenue  operating_profit    net_income  \
0           2020-03-31  1.732064e+12      2.214951e+11  1.348746e+11
1           2020-06-30  1.902468e+12      2.305976e+11  9.068220e+10
2           2020-09-30  1.360779e+12      2.917268e+11  2.353430e+11
3           2020-12-31  5.304146e+12      1.215342e+12  8.449970e+11
4           2021-03-31  1.499070e+12      2.888331e+11  1.531452e+13
5           2021-06-30  1.663549e+12      3.356255e+11  5.405520e+11
6           2021-09-30  1.727255e+12      3.497720e+11  3.227262e+11
7           2021-12-31  6.817600e+12      1.325478e+12  1.647763e+13
8           2022-03-31  1.845222e+12      3.017872e+11  1.513982e+11
9           2022-06-30  2.045781e+12      3.361511e+11  1.584744e+11
10          2022-09-30  2.057332e+12      3.302433e+11  2.315544e+11
11          2022-12-31  8.220079e+12      1.304664e+12  6.731803e+11
12          2023-03-31  2.280443e+12      3.304921e+11  4.365522e+10
13          2023-06-30  2.407904e+12      3.726565e+11  2.867154e+11
14          2023-09-30  2.445292e+12      3.801807e+11  3.562068e+11
15          2023-12-31  9.670644e+12      1.488820e+12  9.850178e+11
16          2024-03-31  2.526055e+12      4.392931e+11  5.558033e+11
17          2024-06-30  2.610486e+12      4.726851e+11  3.320565e+11
18          2024-09-30  2.715557e+12      5.252697e+11  5.300778e+11
19          2024-12-31  1.073772e+13      1.979263e+12  1.931976e+12
20          2025-03-31  2.786783e+12      5.053013e+11  4.236613e+11
21          2025-06-30  2.915085e+12      5.215537e+11  4.973583e+11
22          2025-09-30  3.138055e+12      5.706468e+11  7.347237e+11
23          2025-12-31  1.203501e+13      2.208138e+12  1.818746e+12

account_nm  debt_ratio  current_ratio  equity_ratio  operating_cf  revenue_yoy
0            84.649190     159.468516     54.156750  2.779451e+11          NaN
1            84.414672     155.208008     54.225620  5.709348e+11          NaN
2           108.487691     140.355087     47.964462  9.463458e+11          NaN
3           106.104985     133.278443     48.518962  1.447212e+12          NaN
4            35.651704     147.993088     73.718204  1.966990e+11   -13.451831
5            36.241984     136.051906     73.398814  5.400605e+11   -12.558364
6            36.169185     124.235893     73.438055  8.697070e+11    26.931321
7            40.219249     140.898005     71.316884  1.379906e+12    28.533412
8            42.359903     136.687760     70.244499  3.202686e+11    23.091109
9            43.986007     145.337945     69.451193  6.919299e+11    22.976915
10           41.444290     124.240399     70.699213  9.298293e+11    19.109914
11           44.556830     117.496827     69.176946  1.453390e+12    20.571448
12           48.289937     106.428577     67.435459  4.461269e+11    23.586352
13           47.754966     111.925121     67.679620  8.146923e+11    17.700968
14           49.269473     113.808058     66.992934  1.417978e+12    18.857443
15           47.445452     111.458250     67.821692  2.002233e+12    17.646606
16           45.864961     131.512438     68.556560           NaN    10.770404
17           44.949707     137.924668     68.989446           NaN     8.413184
18           42.616861     159.512026     70.117936           NaN    11.052448
19           41.357730     153.884846     70.742506  2.589874e+12    11.034175
20           40.258860     126.247831     71.296744  6.067148e+11    10.321545
21           40.862656     129.959178     70.991136  1.124942e+12    11.668293
22           41.594763     134.382452     70.624081  2.151290e+12    15.558406
23           41.900588     136.284213     70.471871  3.095807e+12    12.081597

In [21]:
metrics = {
    'revenue': '매출액',
    'operating_profit': '영업이익',
    'net_income': '당기순이익',
    'revenue_yoy': '매출증가율(YoY,%)',
    'operating_margin': '영업이익률(%)',
    'net_margin': '순이익률(%)',
    'debt_ratio': '부채비율(%)',
    'current_ratio': '유동비율(%)',
    'equity_ratio': '자기자본비율(%)',
    'operating_cf': '영업활동현금흐름',
}

long_rows = []
for col, memo in metrics.items():
    tmp = df[['date', col]].copy()
    tmp = tmp.rename(columns={col: 'value'})
    tmp['memo'] = memo
    long_rows.append(tmp)

long_df = pd.concat(long_rows, ignore_index=True)
long_df = long_df.dropna(subset=['value'])  # NaN(2020 Q1 YoY 등) 제거
long_df = long_df.sort_values(['memo','date']).reset_index(drop=True)

print("최종 long format 데이터 shape:", long_df.shape)
long_df.to_csv('../data/naver_financials.csv', index=False, encoding='utf-8-sig')
long_df.head(15)

최종 long format 데이터 shape: (233, 3)

account_nm        date         value   memo
0           2020-03-31  1.348746e+11  당기순이익
1           2020-06-30  9.068220e+10  당기순이익
2           2020-09-30  2.353430e+11  당기순이익
3           2020-12-31  8.449970e+11  당기순이익
4           2021-03-31  1.531452e+13  당기순이익
5           2021-06-30  5.405520e+11  당기순이익
6           2021-09-30  3.227262e+11  당기순이익
7           2021-12-31  1.647763e+13  당기순이익
8           2022-03-31  1.513982e+11  당기순이익
9           2022-06-30  1.584744e+11  당기순이익
10          2022-09-30  2.315544e+11  당기순이익
11          2022-12-31  6.731803e+11  당기순이익
12          2023-03-31  4.365522e+10  당기순이익
13          2023-06-30  2.867154e+11  당기순이익
14          2023-09-30  3.562068e+11  당기순이익

In [22]:
# ① 유동비율 NaN 원인 확인
print(df[df['current_ratio'].isna()][['date','current_assets','current_liabilities']])

# ② metrics를 9개로 수정 (net_income 제거)
metrics = {
    'revenue': '매출액',
    'revenue_yoy': '매출증가율(YoY,%)',
    'operating_profit': '영업이익',
    'operating_margin': '영업이익률(%)',
    'net_margin': '순이익률(%)',
    'debt_ratio': '부채비율(%)',
    'current_ratio': '유동비율(%)',
    'equity_ratio': '자기자본비율(%)',
    'operating_cf': '영업활동현금흐름',
}

long_rows = []
for col, memo in metrics.items():
    tmp = df[['date', col]].copy()
    tmp = tmp.rename(columns={col: 'value'})
    tmp['memo'] = memo
    long_rows.append(tmp)

long_df = pd.concat(long_rows, ignore_index=True)
long_df = long_df.dropna(subset=['value'])
long_df = long_df.sort_values(['memo','date']).reset_index(drop=True)

print("최종 long format 데이터 shape:", long_df.shape)
long_df.to_csv('../data/naver_financials.csv', index=False, encoding='utf-8-sig')
long_df.head(15)

Empty DataFrame
Columns: [date, current_assets, current_liabilities]
Index: []
최종 long format 데이터 shape: (209, 3)

account_nm        date         value memo
0           2020-03-31  1.732064e+12  매출액
1           2020-06-30  1.902468e+12  매출액
2           2020-09-30  1.360779e+12  매출액
3           2020-12-31  5.304146e+12  매출액
4           2021-03-31  1.499070e+12  매출액
5           2021-06-30  1.663549e+12  매출액
6           2021-09-30  1.727255e+12  매출액
7           2021-12-31  6.817600e+12  매출액
8           2022-03-31  1.845222e+12  매출액
9           2022-06-30  2.045781e+12  매출액
10          2022-09-30  2.057332e+12  매출액
11          2022-12-31  8.220079e+12  매출액
12          2023-03-31  2.280443e+12  매출액
13          2023-06-30  2.407904e+12  매출액
14          2023-09-30  2.445292e+12  매출액

In [23]:
print(long_df.groupby('memo').size())

memo
매출액             24
매출증가율(YoY,%)    20
부채비율(%)         24
순이익률(%)         24
영업이익            24
영업이익률(%)        24
영업활동현금흐름        21
유동비율(%)         24
자기자본비율(%)       24
dtype: int64

In [24]:
print(long_df['memo'].unique())

<StringArray>
[         '매출액', '매출증가율(YoY,%)',      '부채비율(%)',      '순이익률(%)',
         '영업이익',     '영업이익률(%)',     '영업활동현금흐름',      '유동비율(%)',
    '자기자본비율(%)']
Length: 9, dtype: str

In [25]:
missing_cf = df[df['operating_cf'].isna()][['date']]
print(missing_cf)

account_nm        date
16          2024-03-31
17          2024-06-30
18          2024-09-30

In [26]:
# 결측치 처리: 2024 Q1~Q3 영업활동현금흐름 결측 → 직전 분기값으로 대체
before = long_df[long_df['memo']=='영업활동현금흐름'].shape[0]

# df(wide 형태)에서 직접 보정 후 다시 long 변환하는 게 더 정확함
df['operating_cf'] = df['operating_cf'].fillna(method='ffill')

# operating_cf만 다시 long으로 변환해서 교체
cf_long = df[['date','operating_cf']].rename(columns={'operating_cf':'value'})
cf_long['memo'] = '영업활동현금흐름'
cf_long = cf_long.dropna(subset=['value'])

long_df = long_df[long_df['memo'] != '영업활동현금흐름']
long_df = pd.concat([long_df, cf_long], ignore_index=True)
long_df = long_df.sort_values(['memo','date']).reset_index(drop=True)

after = long_df[long_df['memo']=='영업활동현금흐름'].shape[0]
print(f"영업활동현금흐름 결측 처리: {before}개 → {after}개")
print("최종 shape:", long_df.shape)

long_df.to_csv('../data/naver_financials.csv', index=False, encoding='utf-8-sig')

TypeError: NDFrame.fillna() got an unexpected keyword argument 'method'

In [27]:
df['operating_cf'] = df['operating_cf'].ffill()

In [28]:
before = long_df[long_df['memo']=='영업활동현금흐름'].shape[0]

df['operating_cf'] = df['operating_cf'].ffill()

cf_long = df[['date','operating_cf']].rename(columns={'operating_cf':'value'})
cf_long['memo'] = '영업활동현금흐름'
cf_long = cf_long.dropna(subset=['value'])

long_df = long_df[long_df['memo'] != '영업활동현금흐름']
long_df = pd.concat([long_df, cf_long], ignore_index=True)
long_df = long_df.sort_values(['memo','date']).reset_index(drop=True)

after = long_df[long_df['memo']=='영업활동현금흐름'].shape[0]
print(f"영업활동현금흐름 결측 처리: {before}개 → {after}개")
print("최종 shape:", long_df.shape)

long_df.to_csv('../data/naver_financials.csv', index=False, encoding='utf-8-sig')

영업활동현금흐름 결측 처리: 21개 → 24개
최종 shape: (212, 3)